### ISSUE TITLE
Possible to add support for EM6514

### ISSUE THREAD

**Issue by Flight777** [athombv/com.e-domotica#1]
Hi,

Would it be possible to add support for the Z-wave switch (remote) EM6514?

Let me know if you would need anything! 👍

https://www.domotica-shop.nl/e-domotica-em6514-inbouwsensor-restpartij1-jaar-garantie-p-16397.html

**Comment by RobinBol** [comment]
Thanks for reporting! The E-Domotica app has been taken over by Domotica-Shop, they did not update the app yet so it still points to our repository. It would be best to contact Domotica-Shop with your request directly.
